// APP
export const APP_GET_USER = 'APP/GET_USER';
export const APP_CHANGE_ITEMS_PER_PAGE = 'APP/CHANGE_ITEMS_PER_PAGE';
export const APP_SOMETHING_WENT_WRONG = 'APP/SOMETHING_WENT_WRONG';

// POKEMONS
export const POKEMONS_GET_POKEMONS = 'POKEMONS/GET_POKEMONS';
export const POKEMONS_UPDATE_POKEMONS = 'POKEMONS/UPDATE_POKEMONS';
export const POKEMONS_CATCH_POKEMON = 'POKEMONS/CATCH_POKEMON';
export const POKEMONS_RELEASE_POKEMON = 'POKEMONS/RELEASE_POKEMON';
